In [1]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [2]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [3]:
#  기존 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [5]:
# 오름차순 정렬
a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [8 7 0 4 1]
    


In [6]:
# 1. np.sort(자료) -> 원본 자체가 바뀌지 않음
np.sort(a)

array([0, 1, 4, 7, 8])

In [7]:
a

array([8, 7, 0, 4, 1])

In [9]:
# 2. 자료.sort() - > 원본 자료 변경
a.sort()
a

array([0, 1, 4, 7, 8])

In [10]:
a

array([0, 1, 4, 7, 8])

In [11]:
b = np.random.randint(0, 10, 5)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [8 3 4 1 2]
    


In [12]:
# np.argsort(자료)는 자료 내부의 아이템들을 오름차순 정렬하기 위해서
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
np.argsort(b)

array([3, 4, 1, 2, 0], dtype=int64)

In [13]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
a = np.random.random((3, 3))
b = np.random.random((3, 3))
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.52324166 0.12727994 0.04782438]
 [0.27343199 0.66826177 0.25240507]
 [0.85909991 0.99152593 0.23394408]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.06124975 0.92969672 0.88531881]
 [0.07621261 0.17114876 0.98174586]
 [0.15769202 0.62248767 0.13088314]]
    


##### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (열 별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [14]:
# 기본 방향(axis = -1)
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.52324166 0.12727994 0.04782438]
 [0.27343199 0.66826177 0.25240507]
 [0.85909991 0.99152593 0.23394408]]
    


array([[0.04782438, 0.12727994, 0.52324166],
       [0.25240507, 0.27343199, 0.66826177],
       [0.23394408, 0.85909991, 0.99152593]])

##### axis = 0 (열 기준 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [15]:
# 열 별 정렬
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.52324166 0.12727994 0.04782438]
 [0.27343199 0.66826177 0.25240507]
 [0.85909991 0.99152593 0.23394408]]
    


array([[0.27343199, 0.12727994, 0.04782438],
       [0.52324166, 0.66826177, 0.23394408],
       [0.85909991, 0.99152593, 0.25240507]])

In [21]:
a = np.random.random((3,3))
a

array([[0.84309399, 0.13822191, 0.64460692],
       [0.56754622, 0.20806277, 0.85631708],
       [0.5244498 , 0.92838732, 0.45220006]])

In [17]:
a.reshape(1, 9).sort() # 1차원 배열로 변경 후 정렬

In [18]:
a

array([[0.04782438, 0.12727994, 0.23394408],
       [0.25240507, 0.27343199, 0.52324166],
       [0.66826177, 0.85909991, 0.99152593]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [23]:
# 0부터 29까지의 1씩 증가하는 값을 아이템으로 가지는 1차원 배열 생성
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [25]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소 접근
arr1[1]

1

In [27]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [28]:
# 1차원 배열 인덱싱을 통한 값 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [29]:
# 배열 arr1을 이용해 4 x 6 형태의 2차원 배열 arr2 만들기
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [30]:
# 2차원 배열 인덱싱 : 2차원 배열(행인덱스, (열인덱스))
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [31]:
# 하나의 행에 접근 :  모든 열에 대해서 하나의 행에 접근
# 반환값 : 1d array
arr2[:, 0] # : -> 세로 줄 전체 0 -> 0 번째 열만 가져오기 

array([ 0,  6, 12, 18])

In [32]:
# 하나의 값에 접근
# 3행 3열
arr2[2, 2]

14

In [33]:
# 여러 개의 행 조회
arr2[[0, 3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [34]:
# 여러 개의 세로 줄(열) 조회
arr2[:, [0, 2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [35]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하는 값을 스칼라 값으로 전달
# 서로 다른 값으로 수정 : 배열 요호 개수에 맞춰서 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [36]:
# 단일 값이 아닌 여러 값을 대입하고 싶을 때는
arr2[1] = [9, 9, 9, 99, 99, 99] # 개수를 맞춰서
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [37]:
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  9   9   9  99  99  99]
 [  9   9   9   9   9   9]
 [ 18  19  20  21  22 100]]
    


In [38]:
# 3차원 배열 생성
# 구조 : 2개의 층, 4행 3열
# np.arange() => 24개의 size
arr3 = np.arange(0, 24).reshape((2, 4, 3)) # 2장의 4 x 3 배열
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (2, 4, 3)  
    dimension : 3  
    dtype : int32
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [39]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
# 첫 번째 면, 1번 행에 접근
arr3[0, 1]

array([3, 4, 5])

In [42]:
arr3[0][1]

array([3, 4, 5])

In [43]:
# 첫 번째 면, 1번 행, 0번 열에 접근
arr3[0, 1, 0]

3

In [44]:
arr3[0][1][0]

3

In [45]:
# 3차원 배열 역시 배열 인덱싱으로 값 수정이 가능하다.
# 스칼라 연산을 통한 동일한 값으로 수정
# arr3의 2번 면(1번 인덱스)를 0으로 일괄 변경해주세요
arr3[1] = 0

In [46]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [47]:
# 하나의 면에 대해 서로 다른 값으로 수정 : 요소의 값을 같은 구조, 개수로 전달
arr3[1, 1] = [1, 2, 3]
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [50]:
arr3[0] = [[10, 20, 30],
         [40, 50, 60],
         [0, 0, 0],
         [0, 0, 0]]

In [51]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [54]:
# 인덱스 배열을 전달하여 여러 개의 요소 참조
# (기존 인덱싱 방법) 0번재 장 0행 0열, 1행 1열, 2행 2열 요소에 접근
arr3[0, 0, 0] # 10
arr3[0, 1, 1] # 50
arr3[0, 2, 2] # 0

0

In [55]:
# 여러 개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [0, 1, 2], [0, 1, 2]]
# arr3[면, 행, 열] -> 만약 여러 단위를 조회할 때는 이중리스트로 입력
# 삼중리스트로 입력시 이중리스트 요소를 반복
arr3[0, [[0, 1, 2], [0, 1, 2]]]

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]]])

In [56]:
# 내부 요소 인덱싱시 일반 리스트를 사용하는 경우
# 줄 단위로 가져오는게 아니라 내부 요소 하나하나 단위로 가져옴
arr3[0, [0, 1, 2], [0, 1, 2]]

array([10, 50,  0])

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [86]:
# 0부터 23까지 1씩 증가하는 정수 값을 가지는 1차원 배열 생성
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [87]:
# 1차원 배열 슬라이싱 : 1번 인덱스부터 4번 인덱스까지 접근
a[1:5]

array([1, 2, 3, 4])

In [88]:
# 1번째 인덱스로부터 14번째 인덱스까지 2개씩 건너뛰어 접근
a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [89]:
# 2차원 배열 생성
b = a.reshape(6, 4)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (6, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [81]:
# 2차원 배열 슬라이싱 : 1행부터 4행까지 접근
# 2d array[행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15]])

In [90]:
# 1행부터 4행에 대해서 2열부터 4열까지 접근
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [91]:
# 2차원 배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지의 모든 배열에 대해
s_arr = b[1:5, 2:]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [92]:
# 0 번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, :-1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [93]:
# 원본 배열의 변경 여부 확인
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [94]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열에 대한 인덱싱
# step1. 전체 행에 대하여 접근
# step2. 여러 개의 열 인덱싱 배열 전달
# b의 전체 행 + 1, 3번째 열
# b[행, 열]
b[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제 (v)

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [96]:
st = [[1, 2, 3, 4],
     [70, 97, 45, 56],
     [87, 84, 33, 67],
     [46, 80, 75, 78]]
arr = np.array(st)

In [97]:
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (4, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4]
 [70 97 45 56]
 [87 84 33 67]
 [46 80 75 78]]
    


In [98]:
# 영어 성적을 기준으로 오름차순으로 정렬
np.sort(arr) 

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [33, 67, 84, 87],
       [46, 75, 78, 80]])

In [118]:
# 영어 설적을 기준으로 오름차순 정렬 순위 (srgsort() 기능 사용하기)
i = np.argsort(arr[1])
i

array([2, 3, 0, 1], dtype=int64)

In [121]:
arr[0, i]
arr[:, [2, 3, 0, 1]]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

In [ ]:
arr[0] = arr[0, i]
arr[1] = arr[1, i]
arr[2] = arr[2, i]
arr[3] = arr[3, i]

In [ ]:
arr

### 조건 색인(Boolean Indexing)

- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [122]:
# 2차원 배열 확인
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [123]:
# 스칼라 연산을 통해 10보다 큰 요소 조회
b > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [126]:
# 조건 색인 방법
# 자료[자료를 포함한 조건식]
b[b>10]

array([99, 11, 12, 13, 99, 15, 16, 17, 99, 19, 20, 21, 22, 23])

In [127]:
b[b>10].size

14

In [132]:
# 조건 색인을 이용해 짝수인 자료만 남겨보세요
# 조건색인시 2개이상의 조건을 걸고 싶을 때는 각 조건을 하나하나마다 ()로 감싸주고
# 조건 사이를 and인 경우에는 &로 or인 경우에는 |로 연결해준다
b[(b%2==0) & (b != 0)]

array([ 2,  4,  6,  8, 12, 16, 20, 22])

### 연습문제

조건색인을 활용해 공무원시험의 합격자 평균을 구해주세요.
합격점수는 60점 이상입니다.

아래는 시험 점수 결과입니다.<br>
[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51]

In [138]:
data = [31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34, 55, 56, 51]
test = np.array(data)

In [154]:
arr5 = test[test>=60]

In [155]:
arr5

array([83, 75, 86, 60, 94, 80, 73, 80, 65])

In [156]:
sum_ = 0
avg = 0
for t in arr5:
    sum_ += t
avg = sum_/len(arr5)

In [157]:
avg

77.33333333333333

In [158]:
test[test>=60].mean()

77.33333333333333

### 배열복사

- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성 : arr.copy() / np.copy(arr)

In [159]:
a = [1, 2, 3]
a2 = [1, 2, 3]

In [160]:
# 얕은 복사
b = a

In [161]:
# 깊은 복사 1
c = a2[:]

In [162]:
b[0] = 10
c[0] = 10

In [165]:
a, a2

([10, 2, 3], [1, 2, 3])

In [166]:
b, c

([10, 2, 3], [10, 2, 3])

In [167]:
# 0부터 3까지 범위로 1씩 증가하는 2 x 2 구조 배열 생성
arr1 = np.arange(0, 4).reshape(2, 2)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (2, 2)  
    dimension : 2  
    dtype : int32
    data :
 [[0 1]
 [2 3]]
    


In [168]:
# 깊은 복사 2 
arr2 = arr1.copy()

In [169]:
# 얕은 복사
arr3 = arr1

In [170]:
arr2[0, 0] = 100

In [171]:
arr1

array([[0, 1],
       [2, 3]])

In [172]:
arr2

array([[100,   1],
       [  2,   3]])

In [173]:
arr3[0, 0] =  100

In [174]:
arr3

array([[100,   1],
       [  2,   3]])

In [175]:
arr1

array([[100,   1],
       [  2,   3]])