In [2]:
# 라이브러리 불러오기
import numpy as np

In [3]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체 타임, 구조, 차원, 데이터타입
def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [4]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열
a = np.arange(1, 10).reshape(3, 3)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 4부터 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4, 13).reshape(3, 3)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# 10 ~ 21까지 3행 4열 형태로 만들기
c = np.arange(10, 22).reshape(3, 4)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [7]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# 산술 연산자
a + b # 같은 위치에 있는 것들이랑 더해줌

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [9]:
# 메서드 활용
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [10]:
# 구조가 다른 배열 간의 산술 연산시 에러 발생(+)
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기

- 배열 - 배열
- np.subtract(arr1, arr2)

In [11]:
# 산술연산자
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [12]:
b - a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [13]:
# 메서드 활용
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [14]:
np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 나누기

- 배열 / 배열
- np.divide(arr1, arr2)

In [15]:
# 산술 연산자
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [16]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [17]:
# 메서드 활용
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [18]:
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

### 곱하기

- 배열 * 배열
- np.multiply(arr1, arr2)

In [19]:
# 산술 연산자
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [20]:
b * a

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [21]:
# 메서드 사용
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [22]:
np.multiply(b, a)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 10의 2제곱 = 214 / 2.98e-8 = 2.98 x 10의 -8제곱 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 지수 함수
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [25]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)

- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [26]:
a * b # 행렬 곱이 아님

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [28]:
np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [29]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Numpy 배열 연산

#### 2. 비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <. >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [30]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
# 두 배열 요소에 대하여 값이 동일한지를 비교
# 반환 : 각 요소마다의 비교결과(T/F)가 배열로 표현됨
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [32]:
np_print(a==b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : bool
    array data : 
 [[False False False]
 [False False False]
 [False False False]]


In [33]:
# 두 배열 요소에 대하여 값이 다른지 비교
a != b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
# 두 배열 요소에 대해 크기 비교
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
# 두 배열이 완전히 일치하는지 여부만 조회
# 하나의 T/F로 반환
np.array_equal(a, b)

False

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median() ★
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef() ★
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [36]:
# 사용할 배열 객체 확인
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# 합계 - 전체 기준 => 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy 함수 : np.sum(arr)
a.sum()

45

In [38]:
np.sum(a)

45

In [39]:
# 합계 - row, 가로축 기준
# 메서드, np 함수의 파라미터 값 : axis=1
# 결과값 : [첫 행 합계, 두 번째 행 합계, 세 번째 행 합계 ..]
print(c.sum(axis=1))
print(c)

[46 62 78]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [40]:
# 합계 - column, 세로축 기준
# 메서드, np함수의 파라미터 값 : axis=0
# 결과값 : [첫 번째 열 합, 두 번째 열합, 세 번째 열 합]
print(c.sum(axis=0))
print(c)

[42 45 48 51]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [41]:
# 최소값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy 함수 : np.min(arr)
c.min()
np.min(c)

10

In [42]:
# (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [43]:
# 최소값 - 각 가로축 별 최소값 찾기
# 결과값 : [첫 번째 행 최소값, 두 번째 행 최소값 ...]
print(c.min(axis=1))
print(c)
print(np.min(c, axis=1))

[10 14 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 14 18]


In [44]:
# 최소값 - 각 세로축 별 최소값 찾기
# 결과값 : [첫 번째 행 최소값, 두 번째 행 최소값 ...]
print(c.min(axis=0))
print(c)
print(np.min(c, axis=0))

[10 11 12 13]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13]


In [45]:
# 최대값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.max()
# 2) numpy 함수 : np.max(arr)
print(c.max())
print(np.max(c))

21
21


In [46]:
# 최대값 가로축 기준
print(c.max(axis=1))
print(np.max(c, axis=1))

[13 17 21]
[13 17 21]


In [47]:
# 최대값 세로축 기준
print(c.max(axis=0))
print(np.max(c, axis=0))

[18 19 20 21]
[18 19 20 21]


In [48]:
# 누적합계 - 전체 기준
# 1) 배열 타입의 메서드: c.cumsum()
# 2) numpy 함수 np.cumsum()
# 결과값 :
c.sum()

186

In [49]:
c.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165, 186],
      dtype=int32)

In [50]:
# 누적 합계 - 가로축 기준
print(c.cumsum(axis=1))
print(np.cumsum(c, axis=1))
print(c)

[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [51]:
# 누적 합계 - 세로축 기준
print(c.cumsum(axis=0))
print(np.cumsum(c, axis=0))

[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]
[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]


In [54]:
# 평균 - 전체 기준
# 1) 배열 타입의 메서드 : arr.mean()
# 2) numpy 함수 : np.mean(arr)
print(c)
print(c.mean())
print(np.mean(c))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
15.5
15.5


In [55]:
# 평균 - 가로축 기준
print(c.mean(axis=1))
print(np.mean(c, axis=1))

[11.5 15.5 19.5]
[11.5 15.5 19.5]


In [56]:
# 평균 - 세로축 기준
print(c.mean(axis=0))
print(np.mean(c, axis=0))

[14. 15. 16. 17.]
[14. 15. 16. 17.]


In [57]:
# 중앙값 - 전체 기준
# numpy 함수 : np.median()
# arr.medisn()은 존재하지 않음
np.median(c) # 짝수 개수이기 때문에 가운데의 두 값인 15, 16을 더해서 2로 나눈값을 출력

15.5

In [59]:
# 중앙값 - 가로축 기준
np.median(a, axis=1)

array([2., 5., 8.])

In [60]:
# 중앙값 - 세로축 기준
np.median(a, axis=0)

array([4., 5., 6.])

In [61]:
# 상관계수 : 두 데이터 간의 상관 관계(양/음의 상관관계)
# 1 : 하나가 올라갔는데 또 다른 하나가 무조건 올라갈 것이라고 예상되는 경우
# 0: 상관없음(다른 하나의 수치가 올라갔는데 예측할 수 없음 ) 
# -1 : 하나가 올라갔는데 또 다른 하나가 무조건 내려갈 것이라고 예상되는 경우
# numpy 함수 : np.sorrcoef(arr1, arr2)
x = np.array([15, 12, 27, 37, 29])
y = np.array([1, 4, 2, 9, 7])

In [62]:
# 자기 자신을 대상으로 한 상관 관계(무조건 1)
np.corrcoef(x, x)

array([[1., 1.],
       [1., 1.]])

In [64]:
# 서로 다른 배열 2개를 활용한 상관계수 matrix
# 결과 : 대칭형 매트릭스(대각선을 경계로 상위, 하위 삼각형 중 하나만 해석해도 된다.)
# 오른쪽 아래로 향하는 대각선은 자기 자신과의 상관관계(항상 1)
print(x)
print(y)
print(np.corrcoef(x, y)) # 두 번은 일치, 두 번은 불 일치, 음수가 안나옴 : 대체로 따라가는 것 같다
'''   
      x           y
x [[1.         0.72615657]
y [0.72615657 1.        ]]
'''

[15 12 27 37 29]
[1 4 2 9 7]
[[1.         0.72615657]
 [0.72615657 1.        ]]


In [65]:
# numpy에서는 3개 요소를 아용한 상관도를 구하는 것이 불가능
# 팬더스를 이용하는 경우는 2개씩 조합한 모든 경우의 수를 구해준다.
z = np.array([0.3, 0.5, 0.6, 0.8, 1.3])

In [66]:
np.corrcoef(x, y, z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [67]:
# 표준편차 - 전체 기준
# 1) 배열 타입의 메서드 - arr.std()
# 2) numpy 함수 : np.std(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a.std()

2.581988897471611

#### (참고) 데이터가 퍼져있는 정도를 나타내는 개념

1. 편차(std/sd) : 단위에 대한 보정이 들어가 있지 않아서 상대적인 비교가 어려움
2. 변동계수(cv) : 편차/평균
    - 두 개 이상의 변수(서로 다른 단위를 사용하는 경우)에 대해 데이터가 퍼져있는 정도를 파악하는 경우